#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b --experimental-backends &
feh --bg-fill $HOME/.local/share/wallpapers/at1.jpg &
~/.config/polybar/launch.sh

# Workspaces
bspc monitor -d I II III IV V

# Other
bspc config border_radius	0
bspc config border_width	0
bspc config window_gap		10
bspc config split_ratio		0.6
